import {test, expect} from '@playwright/test';

test('Empresa: inferencia real, descripción editable y cambio de rol sin datos anteriores', async ({page, context}) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write']);
  await page.goto('/');
  await expect(page.getByRole('heading', {name:'¿Eres empleado o empresa?'})).toBeVisible();
  await expect(page.getByText('Prototipo local · Modelo entrenado con datos sintéticos · Sin registro')).toHaveCount(0);
  await page.getByRole('button', {name:'Soy empresa',exact:true}).click();
  await page.getByLabel('Puesto de la vacante').selectOption('Personal de control de almacén');
  await page.getByLabel('Años de experiencia requeridos').fill('0');
  await page.getByLabel('Horas semanales de la vacante').fill('40');
  const respuesta = page.waitForResponse('**/api/estimar-perfil?incluir_orientacion=false');
  await page.getByRole('button', {name:'Estimar banda de la vacante'}).click();
  const api = await respuesta;
  expect(api.status()).toBe(200);
  expect(api.request().postDataJSON()).toMatchObject({experiencia_anios:0, horas_semana:40, tiene_dc3:0});
  const datos = await api.json();
  expect(datos.orientacion).toBeNull();
  await expect(page.locator('.kpi.featured .amount')).toHaveText(new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',minimumFractionDigits:2,maximumFractionDigits:2}).format(datos.salario.mediana_p50));
  await expect(page.getByRole('button',{name:'Crear mi CV en PDF'})).toHaveCount(0);
  await page.getByRole('button',{name:'Crear descripción de empleo'}).click();
  const texto = page.getByLabel('Texto de la vacante');
  const borrador = await texto.inputValue();
  expect(borrador).toContain('Sin experiencia previa requerida.');
  expect(borrador).toContain('No se requiere licencia');
  expect(borrador).toContain('40 horas semanales');
  expect(borrador).toContain('Sin constancias DC-3 requeridas');
  await texto.fill(borrador + '\nEmpresa de ejemplo: enviar solicitud por correo.');
  await page.getByRole('button',{name:'Copiar descripción'}).click();
  await expect(page.getByRole('status')).toContainText('Descripción copiada');
  expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('Empresa de ejemplo');
  await page.getByRole('button',{name:'Ver banda salarial'}).click();
  await page.getByRole('button',{name:'Crear descripción de empleo'}).click();
  await expect(texto).toHaveValue(/Empresa de ejemplo/);
  await page.getByRole('button',{name:'Cambiar empleado / empresa'}).click();
  await page.getByRole('button',{name:'Soy empleado',exact:true}).click();
  await expect(page.getByLabel('Puesto / oficio')).toHaveValue('Conductores de carga');
  await expect(page.getByRole('button',{name:'Explorar mi banda salarial'})).toBeVisible();
  await expect(page.getByLabel('Texto de la vacante')).toHaveCount(0);
});

test('Empresa: error permite reintentar; requisitos y móvil', async ({page}) => {
  await page.setViewportSize({width:390,height:844});
  await page.goto('/');
  await page.screenshot({path:'test-results/seleccion-rol-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Soy empresa',exact:true}).click();
  await page.getByLabel('Licencia requerida').selectOption('Federal E');
  await page.getByRole('checkbox',{name:'Manejo Defensivo',exact:true}).check();
  await page.route('**/api/estimar-perfil?*', route => route.abort());
  await page.getByRole('button',{name:'Estimar banda de la vacante'}).click();
  await expect(page.getByRole('alert')).toContainText('conectar');
  await expect(page.locator('.kpi')).toHaveCount(0);
  await page.unroute('**/api/estimar-perfil?*');
  await page.getByRole('button',{name:'Estimar banda de la vacante'}).click();
  await page.getByRole('button',{name:'Crear descripción de empleo'}).click();
  await expect(page.getByLabel('Texto de la vacante')).toHaveValue(/Licencia requerida: Federal E/);
  await expect(page.getByLabel('Texto de la vacante')).toHaveValue(/Manejo Defensivo/);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/vacante-mobile.png',fullPage:true});
});
